[package]
name = "ascii-shade-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.69", features = ["full", "parsing"] }

[lib]
proc-macro = true
